<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" 
schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cf_tracking</name>
  <version>0.1.0</version>
  
  <description>Crazyflie 2.1+ quadrotor trajectory tracking sim package
  with different controllers(Lee/Mellinger/MPC over direct motor speed 
  commands)</description>
  
  <maintainer email="rakshithajetaravi@gmail.com">Rakshith Ajetaravi
  </maintainer>
  
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>actuator_msgs</depend>
  <depend>ros_gz_bridge</depend>
  <depend>ros_gz_sim</depend>
  
  <depend>python3-yaml</depend>
  <depend>python3-scipy</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
